VWA-MarkTest/src/objects/Accomplishment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acreage Impacted</fullName>
                </value>
                <value>
                    <fullName>Buckwheat Plants Removed</fullName>
                </value>
                <value>
                    <fullName>Buckwheat Plants Trimmed</fullName>
                </value>
                <value>
                    <fullName>Campsites Cleaned / Enhanced</fullName>
                </value>
                <value>
                    <fullName>Campsites Removed</fullName>
                </value>
                <value>
                    <fullName>Fire Permits Issued</fullName>
                </value>
                <value>
                    <fullName>LBS of Trash Removed</fullName>
                </value>
                <value>
                    <fullName>Logs Removed</fullName>
                </value>
                <value>
                    <fullName>Miles of Trail Monitored</fullName>
                </value>
                <value>
                    <fullName>Structures Built</fullName>
                </value>
                <value>
                    <fullName>Structures Maintained</fullName>
                </value>
                <value>
                    <fullName>Violations Observed</fullName>
                </value>
                <value>
                    <fullName>Visitor Contacts</fullName>
                </value>
                <value>
                    <fullName>Yards of Trail (Re)Constructed</fullName>
                </value>
                <value>
                    <fullName>Yards of Trail Brushed</fullName>
                </value>
                <value>
                    <fullName>Yards of Tread Maintained</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>GW_Volunteers__Volunteer_Job__c</referenceTo>
        <relationshipLabel>Accomplishments</relationshipLabel>
        <relationshipName>Accomplishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Accomplishment</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Accomplishment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accomplishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VWA-MarkTest/src/objects/GW_Volunteers__Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>GW_Volunteers__Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VWA-MarkTest/src/classes/AccomplishmentCtlTest.cls
@isTest
private class AccomplishmentCtlTest {

	static GW_Volunteers__Volunteer_Job__c job;
	static PageReference pageRef = Page.JobAccomplishments;
	static AccomplishmentCtl ext;		

	private static void init() {
		Campaign camp = new Campaign(Name='Test Campaign');
		insert camp;
		job = new GW_Volunteers__Volunteer_Job__c(
			Name='Test Job',
			GW_Volunteers__Campaign__c = camp.Id
		);
		insert job;
		
		Accomplishment__c accomplishment1 = new Accomplishment__c(
			Type__c = 'Visitor Contacts',
			Amount__c = 10,
			Volunteer_Job__c = job.Id
		);
		insert accomplishment1;
		
		pageRef.getParameters().put('id',job.id);
    	Test.setCurrentPage(pageRef);

    	ApexPages.StandardController con = new ApexPages.StandardController(job);
    	ext = new AccomplishmentCtl(con);		
	}        
    static testMethod void myUnitTest() {
    	init();
    	List<Accomplishment__c> displayList = ext.getDisplayList();
    	for(Accomplishment__c disp : displayList) {
    		if(disp.Id != null) {
    			disp.Amount__c = 0;
    		}
    	}
    	displayList.add(new Accomplishment__c(Type__c='Acreage Impacted', Amount__c = 5, Volunteer_Job__c = job.Id));
    	ext.save();
    	
		List<Accomplishment__c> acList = [
			SELECT Id, Type__c, Amount__c
			FROM Accomplishment__c
			WHERE Volunteer_Job__c = :job.Id
		];
		System.assertEquals(1, acList.size());
		Accomplishment__c ac = acList.get(0);
		System.assertEquals('Acreage Impacted', ac.Type__c);
		System.assertEquals(5, ac.Amount__c);    	
    }
}