VWA-MarkTest/src/objects/Accomplishment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acreage Impacted</fullName>
                </value>
                <value>
                    <fullName>Buckwheat Plants Removed</fullName>
                </value>
                <value>
                    <fullName>Buckwheat Plants Trimmed</fullName>
                </value>
                <value>
                    <fullName>Campsites Cleaned / Enhanced</fullName>
                </value>
                <value>
                    <fullName>Campsites Removed</fullName>
                </value>
                <value>
                    <fullName>Fire Permits Issued</fullName>
                </value>
                <value>
                    <fullName>LBS of Trash Removed</fullName>
                </value>
                <value>
                    <fullName>Logs Removed</fullName>
                </value>
                <value>
                    <fullName>Miles of Trail Monitored</fullName>
                </value>
                <value>
                    <fullName>Structures Built</fullName>
                </value>
                <value>
                    <fullName>Structures Maintained</fullName>
                </value>
                <value>
                    <fullName>Violations Observed</fullName>
                </value>
                <value>
                    <fullName>Visitor Contacts</fullName>
                </value>
                <value>
                    <fullName>Yards of Trail (Re)Constructed</fullName>
                </value>
                <value>
                    <fullName>Yards of Trail Brushed</fullName>
                </value>
                <value>
                    <fullName>Yards of Tread Maintained</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>GW_Volunteers__Volunteer_Job__c</referenceTo>
        <relationshipLabel>Accomplishments</relationshipLabel>
        <relationshipName>Accomplishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Accomplishment</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Accomplishment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accomplishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VWA-MarkTest/src/objects/GW_Volunteers__Volunteer_Job__c.object
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VWA-MarkTest/src/classes/AccomplishmentCtl.cls
public with sharing class AccomplishmentCtl {
    public AccomplishmentCtl(ApexPages.StandardController stdController) {
        this.volunteerJob = (GW_Volunteers__Volunteer_Job__c)stdController.getRecord();
    }
	public GW_Volunteers__Volunteer_Job__c volunteerJob;
    public List<AcDisplay> displayList;
    Map<String, Accomplishment__c> acMap = new Map<String, Accomplishment__c>();
    
    public List<AcDisplay> getDisplayList() {
    	if(displayList == null) {
	    	Schema.DescribeFieldResult fieldResult = Accomplishment__c.Type__c.getDescribe();
	    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
	    	for(Schema.PicklistEntry entry : ple) {
	   			acMap.put(entry.getValue(), 
	   				new Accomplishment__c(Type__c = entry.getValue()));
	    	}
	    	
	    	for(Accomplishment__c acmp : [
					SELECT Id, Type__c, Amount__c 
					FROM Accomplishment__c
					WHERE Volunteer_Job__c = :volunteerJob.Id
					]) 
				{
		    		Accomplishment__c mapped = acMap.get(acmp.Type__c);
		    		mapped.Id = acmp.Id;
		    		mapped.Amount__c = acmp.Amount__c;
		    	}
	    	
	    	displayList = new List<AcDisplay>();
	    	for(String tp : acMap.keySet()) {
	    		Accomplishment__c acmp = acMap.get(tp);
	    		AcDisplay acDisp = new AcDisplay(acmp.id, acmp.Type__c, acmp.Amount__c);
	    		displayList.add(acDisp);
	    	}
    	}
    	return displayList;
    }
    public PageReference save() {
    	List<Accomplishment__c> toUpsert = new List<Accomplishment__c>();
    	List<Accomplishment__c> toDelete = new List<Accomplishment__c>();
    	for(AcDisplay disp : displayList) {
    		if(disp.amount > 0) {
    			toUpsert.add(
    				new Accomplishment__c(Id=disp.Id, Type__c=disp.acType, Amount__c=disp.amount, Volunteer_Job__c=volunteerJob.Id));
    		}
    		else if(disp.Id != null) {
    			toDelete.add(new Accomplishment__c(Id=disp.Id));
    		}
    	}
    	if( ! toUpsert.isEmpty()) {
    		upsert toUpsert;
    	}
    	if(! toDelete.isEmpty()) {
    		delete toDelete;
    	}
        displayList = null;
    	return null;
    }
    public Class AcDisplay {
    	public AcDisplay(String id, String acType, Decimal amount) {
    		this.id=id;
    		this.acType=acType;
    		this.amount=amount;
    	}
    	public String id {get; set;}
    	public String acType {get; set;}
    	public Decimal amount {get; set;}
    }
}