PresenceExercise/PresenceExercise/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Total Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

PresenceExercise/PresenceExercise/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PresenceExercise/PresenceExercise/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Total Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PresenceExercise/PresenceExercise/src/classes/PaymentTriggerHandlerTest.cls
@isTest
private class PaymentTriggerHandlerTest {

    static testMethod void myUnitTest() {
        Contact contact1 = new Contact(FirstName='First1', LastName='Last1');
        insert contact1;
        
        Project__c project1 = new Project__c(Name='Project1');
        insert project1;

        Payment__c payment1 = new Payment__c(Contact__c = contact1.Id, Project__c = project1.Id, Amount__c = 100, Date_Paid__c = System.today()-1);
        Payment__c payment2 = new Payment__c(Contact__c = contact1.Id, Project__c = project1.Id, Amount__c = 150, Date_Paid__c = System.today());
        List<Payment__c> paymentList = new List<Payment__c>();
        paymentList.add(payment1);
        paymentList.add(payment2);  
        
        insert paymentList;
        
        contact1 = [select Last_Payment_Date__c, Total_Payments__c from Contact where Id=:contact1.Id];
        System.assertEquals(System.today(), contact1.Last_Payment_Date__c);
        System.assertEquals(250, contact1.Total_Payments__c);
        
        project1 = [select Total_Payments__c from Project__c where Id=:project1.Id];
        System.assertEquals(250, project1.Total_Payments__c);
        
        delete payment2;
        
        contact1 = [select Last_Payment_Date__c, Total_Payments__c from Contact where Id=:contact1.Id];
        System.assertEquals(System.today()-1, contact1.Last_Payment_Date__c);
        System.assertEquals(100, contact1.Total_Payments__c);
        
        project1 = [select Total_Payments__c from Project__c where Id=:project1.Id];
        System.assertEquals(100, project1.Total_Payments__c);
              
    }
    
}