PresenceExercise/PresenceExercise/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Total Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

PresenceExercise/PresenceExercise/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PresenceExercise/PresenceExercise/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Total Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PresenceExercise/PresenceExercise/src/classes/PaymentTriggerHandler.cls
public with sharing class PaymentTriggerHandler {
    public static void summarizePayments(List<Payment__c> paymentList) {
    	Set<Id> contactIds = new Set<Id>();
    	Set<Id> projectIds = new Set<Id>();
    	for(Payment__c payment : paymentList) {
    		contactIds.add(payment.Contact__c);
    		projectIds.add(payment.Project__c);
    	}
    	List<SObject> toUpdate = new List<SObject>();

    	AggregateResult[] contactSummary = [
    		SELECT
    			Contact__c Id,
    			SUM(Amount__c) totalAmount, 
    			MAX(Date_Paid__c) lastDate 
    		FROM Payment__c
    		WHERE Contact__c IN :contactIds
    		GROUP BY Contact__c
    	];
    	for(AggregateResult ar : contactSummary) {
    		Contact personToUpdate = new Contact(
    			Id=(Id)ar.get('id'),
    			Total_Payments__c=(Decimal)ar.get('totalAmount'),
    			Last_Payment_Date__c=(Date)ar.get('lastDate')
    		);
    		toUpdate.add(personToUpdate);
    	}
    	
    	AggregateResult[] projectSummary = [
    		SELECT
    			Project__c Id,
    			SUM(Amount__c) totalAmount 
    		FROM Payment__c
    		WHERE Project__c IN :projectIds
    		GROUP BY Project__c
    	];
    	for(AggregateResult ar : projectSummary) {
    		Project__c projectToUpdate = new Project__c(
    			Id=(Id)ar.get('id'),
    			Total_Payments__c=(Decimal)ar.get('totalAmount')
    		);
    		toUpdate.add(projectToUpdate);
    	}
    	
    	update toUpdate;
    }
}